spring:
  datasource:
    url: jdbc:postgresql://${AZURE_POSTGRESQL_HOST}:5432/${AZURE_POSTGRESQL_DATABASE}
    username: ${AZURE_POSTGRESQL_USERNAME}
    password: ${AZURE_POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
